apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: admin-service
  name: admin-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: admin-service
