apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mail-server
  name: mail-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mail-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\minikube\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: mail-server
    spec:
      containers:
        - env:
            - name: SMTP_PASSWORD
              value: gjfflbbrhwhbopts
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: shashank2043/tickebook_backend-mail-server:latest
          name: mail-server
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
