apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mail-server
  name: mail-server
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8080
  selector:
    io.kompose.service: mail-server
