apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: monitoring-service
  name: monitoring-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitoring-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\minikube\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: monitoring-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: shashank2043/tickebook_backend-monitoring-service:latest
          name: monitoring-service
          ports:
            - containerPort: 9090
              protocol: TCP
      restartPolicy: Always
