apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: movie-service
  name: movie-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8080
  selector:
    io.kompose.service: movie-service
