apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\minikube\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: auth_db
            - name: MYSQL_PASSWORD
              value: Shashank@123
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_USER
              value: shashank
          image: mysql:8
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: mysql-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-cm1
              subPath: init.sql
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - configMap:
            items:
              - key: init.sql
                path: init.sql
            name: mysql-cm1
          name: mysql-cm1
