apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: show-service
  name: show-service
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    io.kompose.service: show-service
