apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\minikube\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: theatre-service
  name: theatre-service
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8080
  selector:
    io.kompose.service: theatre-service
