spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashank2043/tickebook_config
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0   # trace all requests
    propagation:
      type: B3
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/