spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashank2043/tickebook_config
          default-label: docker
          username: shashank2043
          password: ${GIT_TOKEN}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/